runtime: java
env: flex

handlers:
  - url: /.*
    script: this field is required, but ignored

resources:
  cpu: 1
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
    - name: zen
      volume_type: tmpfs
      size_gb: 0.5

runtime_config:
  jdk: openjdk8
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"

manual_scaling:
  instances: 1